<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-US1NOA4" failures="1" tests="6" name="Test" time="45.294" errors="0" timestamp="2025-01-05T12:37:48 IST">
  <testcase classname="com.mystore.testcases.DataDrivenTests" name="verify_loginDDT" time="1.617"/>
  <testcase classname="com.mystore.testcases.DataDrivenTests" name="verify_loginDDT" time="1.573">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.mystore.testcases.DataDrivenTests.verify_loginDDT(DataDrivenTests.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="com.mystore.testcases.DataDrivenTests" name="verify_loginDDT" time="11.264"/>
  <testcase classname="com.mystore.testcases.DataDrivenTests" name="verify_loginDDT" time="11.76"/>
  <testcase classname="com.mystore.testcases.DataDrivenTests" name="verify_loginDDT" time="1.751"/>
  <testcase classname="com.mystore.testcases.DataDrivenTests" name="verify_loginDDT" time="11.142"/>
</testsuite> <!-- Test -->
